./get-operator-package.sh redhat-operators amq-streams
./get-operator-package.sh redhat-operators codeready-workspaces
./get-operator-package.sh redhat-operators businessautomation-operator
./get-operator-package.sh redhat-operators openshiftansibleservicebroker
./get-operator-package.sh redhat-operators cluster-logging
./get-operator-package.sh redhat-operators elasticsearch-operator
./get-operator-package.sh redhat-operators openshifttemplateservicebroker
./get-operator-package.sh redhat-operators jaeger-product
./get-operator-package.sh redhat-operators amq7-cert-manager
./get-operator-package.sh redhat-operators amq7-interconnect-operator
./get-operator-package.sh redhat-operators kubevirt-hyperconverged
./get-operator-package.sh redhat-operators amq-online
./get-operator-package.sh redhat-operators fuse-online
./get-operator-package.sh redhat-operators datagrid
./get-operator-package.sh redhat-operators 3scale-operator
./get-operator-package.sh redhat-operators servicemeshoperator
./get-operator-package.sh redhat-operators kiali-ossm
./get-operator-package.sh redhat-operators fuse-apicurito
./get-operator-package.sh redhat-operators fuse-camel-k
./get-operator-package.sh redhat-operators serverless-operator
./get-operator-package.sh community-operators etcd
./get-operator-package.sh community-operators prometheus
./get-operator-package.sh community-operators metering
./get-operator-package.sh community-operators jaeger
./get-operator-package.sh community-operators descheduler
./get-operator-package.sh community-operators camel-k
./get-operator-package.sh community-operators node-problem-detector
./get-operator-package.sh community-operators planetscale
./get-operator-package.sh community-operators postgresql
./get-operator-package.sh community-operators strimzi-kafka-operator
./get-operator-package.sh community-operators federation
./get-operator-package.sh community-operators cockroachdb
./get-operator-package.sh community-operators node-network-operator
./get-operator-package.sh community-operators microcks
./get-operator-package.sh community-operators hazelcast-enterprise
./get-operator-package.sh community-operators aqua
./get-operator-package.sh community-operators federatorai
./get-operator-package.sh community-operators myvirtualdirectory
./get-operator-package.sh community-operators opsmx-spinnaker-operator
./get-operator-package.sh community-operators spark-gcp
./get-operator-package.sh community-operators spinnaker-operator
./get-operator-package.sh community-operators twistlock
./get-operator-package.sh community-operators infinispan
./get-operator-package.sh community-operators knative-serving-operator
./get-operator-package.sh community-operators openshift-pipelines-operator
./get-operator-package.sh community-operators knative-eventing-operator
./get-operator-package.sh community-operators opendatahub-operator
./get-operator-package.sh community-operators eclipse-che
./get-operator-package.sh community-operators cert-utils-operator
./get-operator-package.sh community-operators atlasmap-operator
./get-operator-package.sh community-operators knative-camel-operator
./get-operator-package.sh community-operators apicurito
./get-operator-package.sh community-operators triggermesh
./get-operator-package.sh community-operators microsegmentation-operator
./get-operator-package.sh community-operators namespace-configuration-operator
./get-operator-package.sh community-operators syndesis
./get-operator-package.sh community-operators knative-kafka-operator
./get-operator-package.sh community-operators seldon-operator
./get-operator-package.sh community-operators open-liberty
./get-operator-package.sh community-operators radanalytics-spark
./get-operator-package.sh community-operators akka-cluster-operator
./get-operator-package.sh community-operators kiali
./get-operator-package.sh community-operators ibmcloud-operator
./get-operator-package.sh community-operators hco-operatorhub
./get-operator-package.sh community-operators enmasse
./get-operator-package.sh community-operators openebs
./get-operator-package.sh community-operators ripsaw
./get-operator-package.sh community-operators grafana-operator
./get-operator-package.sh community-operators awss3-operator-registry
./get-operator-package.sh community-operators esindex-operator
./get-operator-package.sh community-operators iot-simulator
./get-operator-package.sh community-operators t8c
./get-operator-package.sh community-operators kubeturbo
./get-operator-package.sh community-operators event-streams-topic
./get-operator-package.sh community-operators hawtio-operator
./get-operator-package.sh community-operators appsody-community-operator
./get-operator-package.sh community-operators maistraoperator
./get-operator-package.sh community-operators 3scale-community-operator
./get-operator-package.sh community-operators kubefed
./get-operator-package.sh community-operators postgresql-operator-dev4devs-com
./get-operator-package.sh community-operators teiid
./get-operator-package.sh community-operators smartgateway-operator
./get-operator-package.sh certified-operators mongodb-enterprise
./get-operator-package.sh certified-operators couchbase-enterprise-certified
./get-operator-package.sh certified-operators sysdig-certified
./get-operator-package.sh certified-operators planetscale-certified
./get-operator-package.sh certified-operators robin-operator
./get-operator-package.sh certified-operators storageos
./get-operator-package.sh certified-operators hazelcast-enterprise-certified
./get-operator-package.sh certified-operators nuodb-ce-certified
./get-operator-package.sh certified-operators newrelic-infrastructure
./get-operator-package.sh certified-operators synopsys-certified
./get-operator-package.sh certified-operators oneagent-certified
./get-operator-package.sh certified-operators insightedge-operator
./get-operator-package.sh certified-operators appdynamics-operator
./get-operator-package.sh certified-operators openunison-ocp-certified
./get-operator-package.sh certified-operators orca
./get-operator-package.sh certified-operators instana-agent
./get-operator-package.sh certified-operators anchore-engine
./get-operator-package.sh certified-operators tidb-operator-certified
./get-operator-package.sh certified-operators mariadb
./get-operator-package.sh certified-operators memql-certified
./get-operator-package.sh certified-operators federatorai-certified
./get-operator-package.sh certified-operators aqua-certified
./get-operator-package.sh certified-operators twistlock-certified
./get-operator-package.sh certified-operators crunchy-postgres-operator
./get-operator-package.sh certified-operators portworx-certified
./get-operator-package.sh certified-operators percona-xtradb-cluster-operator-certified
./get-operator-package.sh certified-operators percona-server-mongodb-operator-certified
./get-operator-package.sh certified-operators kong
./get-operator-package.sh certified-operators sematext
./get-operator-package.sh certified-operators joget-openshift-operator
./get-operator-package.sh certified-operators cic-operator
./get-operator-package.sh certified-operators presto-operator
./get-operator-package.sh certified-operators t8c-certified
./get-operator-package.sh certified-operators kubeturbo-certified
./get-operator-package.sh certified-operators cpx-cic-operator
./get-operator-package.sh certified-operators seldon-operator-certified
./get-operator-package.sh certified-operators appsody-operator-certified
